### PR TITLE
jshint errors for date functions: 1 fixed, 1 ignored. 

### PR DESCRIPTION
**Pull request by friday**
`AQL_DATE_LEAPYEAR()` slightly rewritten to avoid "Confusing use of '!'". It passes your tests.

### CODE REVIEW

**Comment by CoDEmanX** [comment]
Are all 3 comments needed to disable line length check?
Or does either work?
Does `// ignore maxlen jshint check` affect the subsequent line only?

**Comment by CoDEmanX** [comment]
Oh and how do you want to be mentioned as contributor? Github user name, actual name, ?

**Comment by friday** [comment]
This line does absolutely nothing, and could be removed

``` js
//ignore maxlen jshint check
```

While this

``` js
//jshint -W130`
```

turns off the maxlen validation until

``` js
//jshint +W130`
```

turns it back on.

They've done similar exceptions earlier, so I think they'll approve.

friday will do :)

**Comment by friday** [comment]
Should I close this and submit a new without `//ignore maxlen jshint check`?

**Comment by CoDEmanX** [comment]
I made the changed locally, you can kick back and wait for the update :)

BTW: if you add `.patch` to a github PR url, then you get the diff:
https://patch-diff.githubusercontent.com/raw/CoDEmanX/ArangoDB/pull/3.patch

**Comment by friday** [comment]
Cool :)

**Pull request closed without merging**
